version: "3.8"

services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - api
    volumes:
      - ./my_project:/app
      - /app/node_modules
    restart: unless-stopped

  api:
    build:
      context: C:/Users/Jhonatan/Desktop/Backend/ecommerce-api
    ports:
      - "5000:5000"
    volumes:
      - C:/Users/Jhonatan/Desktop/Backend/ecommerce-api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:3000,http://tu-otro-frontend.com
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/ecommerce
    command: npm run dev
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
  mongo-data2:  # Volumen separado para el segundo contenedor de MongoDB
